from abc import ABC, abstractmethod
from logging import Logger
from typing import TYPE_CHECKING, List, Dict
import uuid
from core.game.event_pool import SubscriberQueue
from core.game.manipulators.base_manipulation import BaseManipulation
from core.game.manipulators.melee_attack_manipulation import MeleeAttackManipulator
from core.game.manipulators.movement_manipulator import MovementManipulator
from core.game.manipulators.object_transfer_manipulator import ObjectTransferManipulator
from core.game.manipulators.ranged_attack_manipulation import RangedAttackManipulator
from core.game.manipulators.scene_object_movement_manipulator import SceneObjectMovementManipulator
from core.schemas.in_game import Condition
from skls_generator import Generator
from core.schemas.orchestration import Event, EventTypes
from core.utils.naming_utils import find_fuzzy_matches
if TYPE_CHECKING:
    from core.game.engine import Session
    from core.game.manipulator import Manipulator
    from core.schemas.in_game import Character, NPCCharacter, UnifiedObject, SpellAbility


class   GameEntity(ABC):
    """
    Base class for game entities (Players and NPCs) that contains shared functionality
    including entity-specific manipulators.
    """

    def __init__(self,
                 character: 'Character | NPCCharacter',
                 event_queuee : SubscriberQueue,
                 logger: Logger) -> None:
        self.character = character
        self.event_queue = event_queuee
        self.logger = logger.getChild(self.character.name)
        # Dictionary to store conditional manipulators based on items/spells
        self._conditional_manipulators: Dict[str, 'BaseManipulation'] = {}
        self._session: 'Session | None' = None
        self.default_manipulations = []
        
    def init_default_manipulations(self):
        self.default_manipulations = [
            MovementManipulator,
            ObjectTransferManipulator,
            SceneObjectMovementManipulator,
            MeleeAttackManipulator,
            RangedAttackManipulator
        ]

    @property
    def session(self) -> "Session":
        if self._session is None:
            raise ValueError("Session not injected to a GameEntity!")
        return self._session

    def inject_state(self, state: 'Session') -> None:
        self._session = state
  
    
    def _add_manipulators_for_equipped_items(self):
        """Add manipulators based on equipped items."""
    
    def handle_turn(self):
        if self.character.is_alive:
            self.run()
        else:
            self.logger.warning(f"Character {self.character.name} is dead and unablto take turns")
        
    @abstractmethod
    def run(self) -> None:
        """
        Abstract method that defines the entity's turn logic.
        Should return a list of events generated by the entity's action.
        """
        pass
    
    def death_handle(self):
        self.logger.info(f"💀Character {self.character.name} dies")
        self.event_queue.publish_to_others(Event(
            event_type=EventTypes.ACTION_RESULT, 
            description=f"Character {self.character.name} dies"))
    
    def take_damage(self, damage : int):
        ch = self.character.current_hp
        if ch > 0:
            self.character.current_hp = max(0, self.character.current_hp - damage)
            if self.character.current_hp <= 0:
                self.death_handle()
         
    def remove_condition_by_name(self, name : str):
        def extractor(c : Condition):
            return c.name
        
        condition = find_fuzzy_matches(
            items=self.character.active_conditions_list,
            target=name,
            extractor=extractor
        )
        condition = condition[0] if len(condition) > 0 else None
        if condition:
            self.character.active_conditions_list.remove(condition)
            self.logger.info(f"Character's {self.character.name} condition [{condition.name}] removed.")
            self.event_queue.publish_to_others(Event(
                event_type=EventTypes.ACTION_RESULT,
                description=f"Character's {self.character.name} condition [{condition.name}] removed."
            ))
    
    
    def set_additional_manipulators(self):
        """Checks inventory and stats and assings additiona allowed manipulations for the currect entity."""
        pass


    
    def _get_spatial_context(self, events: list[Event]) -> str:
        """Generate spatial context from recent events."""
        spatial_events = [e for e in events if e.event_type in [
            EventTypes.CHARACTER_POSITION_UPDATE,
            EventTypes.CHARACTER_MOVEMENT
        ]]

        if not spatial_events:
            return "No recent spatial movements detected."

        context = "Recent spatial movements:\n"
        for event in spatial_events:
            context += f"- {event.event_subject} moved to location '{event.event_target}'\n"

        return context

    def get_seen_entities_context(self, max_distance: float = 10.0) -> str:
        """
        Generate context about what this entity can see based on spatial proximity.
        
        Args:
            max_distance: Maximum distance at which this entity can see other entities and objects
            
        Returns:
            A formatted string describing what this entity sees
        """
        if not self._session:
            return "No session context available."
        
        my_position = self.character.position
        current_scene = self._session.current_scene
        current_location = self._session.current_location_name
        
        seen_entities = []
        seen_objects = []
        
        # Check which other characters this entity can see
        for player in self._session.players:
            other_char = player.character
            if other_char.name != self.character.name:  # Don't include self
                distance = self._session.calculate_distance_2d(my_position, other_char.position)
                if distance <= max_distance:
                    seen_entities.append(f"{other_char.name} ({other_char.__class__.__name__[:-9]}) at distance {distance:.2f}")
        
        for npc in self._session.npcs:
            npc_char = npc.character
            if (npc_char.current_scene == current_location and 
                npc_char.name != self.character.name):  # Don't include self
                distance = self._session.calculate_distance_2d(my_position, npc_char.position)
                if distance <= max_distance:
                    seen_entities.append(f"{npc_char.name} ({npc_char.__class__.__name__[:-9]}) at distance {distance:.2f}")
        
        # Check which objects this entity can see
        if current_scene:
            for obj in current_scene.objects:
                if obj.position:
                    distance = self._session.calculate_distance_2d(my_position, obj.position)
                    if distance <= max_distance:
                        seen_objects.append(f"{obj.name} at distance {distance:.2f}")
        
        # Format the visibility info for this entity
        context = f"\n### WHAT {self.character.name.upper()} SEES:\n"
        if seen_entities:
            context += f"Nearby Characters: {', '.join(seen_entities)}\n"
        else:
            context += f"Nearby Characters: None\n"
            
        if seen_objects:
            context += f"Nearby Objects: {', '.join(seen_objects)}\n"
        else:
            context += f"Nearby Objects: None\n"
        
        return context