from abc import ABC, abstractmethod
from logging import Logger
from typing import TYPE_CHECKING, List, Dict
import uuid
from game.event_pool import SubscriberQueue
from game.manipulators.base_manipulation import BaseManipulation
from game.manipulators.melee_attack_manipulation import MeleeAttackManipulator
from game.manipulators.movement_manipulator import MovementManipulator
from game.manipulators.object_transfer_manipulator import ObjectTransferManipulator
from game.manipulators.ranged_attack_manipulation import RangedAttackManipulator
from game.manipulators.scene_object_movement_manipulator import SceneObjectMovementManipulator
from schemas.in_game import Condition
from skls_generator import Generator
from schemas.orchestration import Event, EventTypes
from utils.naming_utils import find_fuzzy_matches
if TYPE_CHECKING:
    from game.engine import Session
    from game.manipulator import Manipulator
    from schemas.in_game import Character, NPCCharacter, UnifiedObject, SpellAbility


class   GameEntity(ABC):
    """
    Base class for game entities (Players and NPCs) that contains shared functionality
    including entity-specific manipulators.
    """

    def __init__(self,
                 character: 'Character | NPCCharacter',
                 event_queuee : SubscriberQueue,
                 logger: Logger) -> None:
        self.character = character
        self.event_queue = event_queuee
        self.logger = logger
        # Dictionary to store conditional manipulators based on items/spells
        self._conditional_manipulators: Dict[str, 'BaseManipulation'] = {}
        self._session: 'Session | None' = None
        self.default_manipulations = []
        
    def init_default_manipulations(self):
        self.default_manipulations = [
            MovementManipulator,
            ObjectTransferManipulator,
            SceneObjectMovementManipulator,
            MeleeAttackManipulator,
            RangedAttackManipulator
        ]

    @property
    def session(self) -> "Session":
        if self._session is None:
            raise ValueError("Session not injected to a GameEntity!")
        return self._session

    def inject_state(self, state: 'Session') -> None:
        self._session = state
  
    
    def _add_manipulators_for_equipped_items(self):
        """Add manipulators based on equipped items."""
    
    def handle_turn(self):
        if self.character.is_alive:
            self.run()
        else:
            self.logger.warning(f"Character {self.character.name} is dead and unablto take turns")
        
    @abstractmethod
    def run(self) -> None:
        """
        Abstract method that defines the entity's turn logic.
        Should return a list of events generated by the entity's action.
        """
        pass
    
    def death_handle(self):
        self.logger.info(f"💀Character {self.character.name} dies")
        self.event_queue.publish_to_others(Event(
            event_type=EventTypes.ACTION_RESULT, 
            description=f"Character {self.character.name} dies"))
    
    def take_damage(self, damage : int):
        ch = self.character.current_hp
        if ch > 0:
            self.character.current_hp = max(0, self.character.current_hp - damage)
            if self.character.current_hp <= 0:
                self.death_handle()
         
    def remove_condition_by_name(self, name : str):
        def extractor(c : Condition):
            return c.name
        
        condition = find_fuzzy_matches(
            items=self.character.active_conditions_list,
            target=name,
            extractor=extractor
        )
        condition = condition[0] if len(condition) > 0 else None
        if condition:
            self.character.active_conditions_list.remove(condition)
            self.logger.info(f"Character's {self.character.name} condition [{condition.name}] removed.")
            self.event_queue.publish_to_others(Event(
                event_type=EventTypes.ACTION_RESULT,
                description=f"Character's {self.character.name} condition [{condition.name}] removed."
            ))
    
    
    def execute_events(self, event_list : list[Event]):
        """Process an event through the appropriate manipulator based on event type and origin."""
        for event in event_list:
            # Validate the event before processing
            pass
        
    def set_additional_manipulators(self):
        """Checks inventory and stats and assings additiona allowed manipulations for the currect entity."""
        pass
